
import Head from 'next/head'
import styles from '../styles/Home.module.css'


import sistyles from '../styles/searchinput.module.css'
// disable ssr
import dynamic from 'next/dynamic'
const SearchInput = dynamic(import('../components/searchinput').then(mod => mod.SearchInput), { ssr: false })



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>SearchInput, a Next.js component</h2>
        <pre>
          {'data = [{"pid": "101", "pname": "apple" }, {"pid": "102", "pname": "banana" }, {"pid": "103", "pname": "orange" }]'}
        </pre>
        <SearchInput
          input_props={{ name: "fruits", default: "", placeholder: "search..." }}
          dropdown={{
            data_or_async_func: [{ "pid": "101", "pname": "apple" }, { "pid": "102", "pname": "banana" }, { "pid": "103", "pname": "orange" }],
            data_id: "mixin_top_assets",
            data_keys: { label: "pname", value: "pid" }
          }}
          style_names={{ container: sistyles.container, inputbox: sistyles.inputbox, dropdownbox: sistyles.dropdownbox, btnclear: sistyles.btnclear }}
        />

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
